// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngvSbbDOIsC03_qtzb4ANqqki9SkYYaA',
    appId: '1:239539294357:web:9e38a464a1a648fcaccb9c',
    messagingSenderId: '239539294357',
    projectId: 'residentreservation',
    authDomain: 'residentreservation.firebaseapp.com',
    storageBucket: 'residentreservation.firebasestorage.app',
    measurementId: 'G-XZ3S88ZMTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzj5F06ezbc8L9V5t_0ti3W4dkYAE3gIM',
    appId: '1:239539294357:android:df91a1d01bcf7a57accb9c',
    messagingSenderId: '239539294357',
    projectId: 'residentreservation',
    storageBucket: 'residentreservation.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbz2guNG9BatbkEEk6Ibc40IdbtIFN6Cg',
    appId: '1:239539294357:ios:2fc1b1102c78293eaccb9c',
    messagingSenderId: '239539294357',
    projectId: 'residentreservation',
    storageBucket: 'residentreservation.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
